server:
  port: 8083

spring:
  application:
    name: ai-parser-service
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: ai-processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # THESE BELONG TO THE CONSUMER (Reading the task)
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.kulubotti.ai_parser_service.event.ExpenseCreatedEvent
    producer:
      # THIS BELONGS TO THE PRODUCER (Sending the result)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/